version: 2
root-markers:
  - .git/
lint-debounce: 0.1s

tools:
  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint'
    lint-formats:
      - '%f:%l DL%n %trror: %m'
      - '%f:%l DL%n %tarning: %m'
      - '%f:%l DL%n %tnfo: %m'
      - '%f:%l DL%n %ttyle: %m'

languages:
  dockerfile:
    - !!merge <<: *dockerfile-hadolint
